(defvar user-emacs-tmp-directory (file-name-concat user-emacs-directory "tmp/"))
(make-directory user-emacs-tmp-directory t)

(add-to-list 'load-path              (file-name-concat user-emacs-directory "lib"))
(add-to-list 'custom-theme-load-path (file-name-concat user-emacs-directory "themes"))

(load-library "packages")
(load-library "editing")
(load-library "sanitize")
(load-library "styles")
(load-library "settings")
(load-library "bindings")
(load-library "display")
(load-library "lsp")
(load-library "projects")
