(defun sanitize-strip-cr ()
    (interactive)
    (while (re-search-forward "\r" nil t)
        (replace-match "")))

(defun sanitize-standardize-source-file ()
    (interactive)
    (delete-trailing-whitespace)
    (untabify (point-min) (point-max))
    (sanitize-strip-cr))

(defun sanitize-standardize-makefile ()
    (interactive)
    (delete-trailing-whitespace)
    (sanitize-strip-cr))
